// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVehicleData() {
  return window['go']['main']['App']['GetVehicleData']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function MoveToCorner(arg1) {
  return window['go']['main']['App']['MoveToCorner'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ScheduleRefresh() {
  return window['go']['main']['App']['ScheduleRefresh']();
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartWidget() {
  return window['go']['main']['App']['StartWidget']();
}

export function ValidateAndSaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateAndSaveConfig'](arg1, arg2, arg3);
}

export function VehicleHomePage() {
  return window['go']['main']['App']['VehicleHomePage']();
}
