// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMockVehicleData() {
  return window['go']['main']['App']['GetMockVehicleData']();
}

export function GetVehicleData() {
  return window['go']['main']['App']['GetVehicleData']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function MoveToCorner(arg1) {
  return window['go']['main']['App']['MoveToCorner'](arg1);
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartDrag() {
  return window['go']['main']['App']['StartDrag']();
}

export function ValidateAndSaveConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateAndSaveConfig'](arg1, arg2);
}
