name: Wails Build

on:
    release:
        types: [created]

env:
    # Necessary for most environments as build failure can occur due to OOM issues
    NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
    build:
        strategy:
            # Failure in one platform build won't impact the others
            fail-fast: false
            matrix:
                build:
                    - name: 'ZEEHO-Widget.exe'
                      platform: 'windows/amd64'
                      os: 'windows-latest'
                      artifact_name: 'ZEEHO-Widget.exe'
                    # - name: 'ZEEHO-Widget'
                    #   platform: 'linux/amd64'
                    #   os: 'ubuntu-latest'
                    #   artifact_name: 'ZEEHO-Widget'

                    # - name: 'ZEEHO-Widget'
                    #   platform: 'darwin/universal'
                    #   os: 'macos-latest'
                    #   artifact_name: 'ZEEHO-Widget'

        runs-on: ${{ matrix.build.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Build wails
              uses: dAppServer/wails-build-action@main
              id: build
              with:
                  build-name: ${{ matrix.build.name }}
                  build-platform: ${{ matrix.build.platform }}
                  package: true
                  go-version: '1.23'
                  wails-version: 'v2.9.0'
                  node-version: '18'
